spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

# Logging
logging.pattern.console=%d{HH:mm:ss} %-5level [%-40.40logger{36}] %msg%n
logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.mongodb.driver=WARN
logging.level.io.netty=WARN
logging.level.reactor.netty=WARN
logging.level.org.springframework.cloud.gateway=WARN
