spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://userservice:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://productservice:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://orderservice:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.server.webflux.routes[3].id=notif-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://notifservice:8085
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/notifications/**
